[workspace]
members = [
    "crates/6grok-core",
    "crates/6grok-agent",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/mbound/6grok"
rust-version = "1.82"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crc = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = { version = "4", default-features = false }
fivegrok-parser = { git = "https://github.com/mbound/5grok-parser", rev = "1d9099d5706a55f4624c8fb01c3a2a09fa5497ad" }
